FROM python:3.12-slim

WORKDIR /app

ENV PYTHONPATH=/app:$PYTHONPATH

RUN pip install --no-cache-dir streamlit psycopg2-binary pandas requests

COPY streamlit_app /app/streamlit_app
COPY src /app/src

WORKDIR /app/streamlit_app

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0", "--server.headless", "true"]
